apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-uhzabbjh
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-uhzabbjh:ee12fc773761dbdc7f9ec264d5e9a7be50b61f87@sha256:d6ae1c750b7345a1b59af15e95033bdf08b70e4e6878b578d85e665b0f479322
        name: container-image  
